"""simplify_deck_model

Revision ID: 2b029f03258c
Revises: 17c3825db287
Create Date: 2026-01-06 12:20:56.946053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2b029f03258c'
down_revision: Union[str, Sequence[str], None] = '17c3825db287'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deck_cards')
    op.add_column('decks', sa.Column('leader_card_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_decks_leader_card_id'), 'decks', ['leader_card_id'], unique=False)
    op.create_foreign_key(None, 'decks', 'cards', ['leader_card_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'decks', type_='foreignkey')
    op.drop_index(op.f('ix_decks_leader_card_id'), table_name='decks')
    op.drop_column('decks', 'leader_card_id')
    op.create_table('deck_cards',
    sa.Column('deck_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('card_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], name=op.f('deck_cards_card_id_fkey')),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], name=op.f('deck_cards_deck_id_fkey')),
    sa.PrimaryKeyConstraint('deck_id', 'card_id', name=op.f('deck_cards_pkey'))
    )
    # ### end Alembic commands ###
