"""Add purchase management tables (stores, purchase_lists, purchase_items, price_entries)

Revision ID: 9dab9ac600e2
Revises: 0c35b5ff07e1
Create Date: 2026-01-30 18:23:19.430755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '9dab9ac600e2'
down_revision: Union[str, Sequence[str], None] = '0c35b5ff07e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(length=7), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='unique_user_store_name')
    )
    op.create_index(op.f('ix_stores_user_id'), 'stores', ['user_id'], unique=False)
    op.create_table('purchase_lists',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('deck_id', sa.Uuid(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_lists_deck_id'), 'purchase_lists', ['deck_id'], unique=False)
    op.create_index(op.f('ix_purchase_lists_user_id'), 'purchase_lists', ['user_id'], unique=False)
    op.create_table('purchase_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('list_id', sa.Uuid(), nullable=False),
    sa.Column('card_id', sa.Uuid(), nullable=True),
    sa.Column('custom_card_id', sa.Uuid(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('selected_store_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['custom_card_id'], ['custom_cards.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['list_id'], ['purchase_lists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['selected_store_id'], ['stores.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_items_list_id'), 'purchase_items', ['list_id'], unique=False)
    op.create_table('price_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['purchase_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'store_id', name='unique_item_store_price')
    )
    op.create_index(op.f('ix_price_entries_item_id'), 'price_entries', ['item_id'], unique=False)
    op.create_index(op.f('ix_price_entries_store_id'), 'price_entries', ['store_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_entries_store_id'), table_name='price_entries')
    op.drop_index(op.f('ix_price_entries_item_id'), table_name='price_entries')
    op.drop_table('price_entries')
    op.drop_index(op.f('ix_purchase_items_list_id'), table_name='purchase_items')
    op.drop_table('purchase_items')
    op.drop_index(op.f('ix_purchase_lists_user_id'), table_name='purchase_lists')
    op.drop_index(op.f('ix_purchase_lists_deck_id'), table_name='purchase_lists')
    op.drop_table('purchase_lists')
    op.drop_index(op.f('ix_stores_user_id'), table_name='stores')
    op.drop_table('stores')
    # ### end Alembic commands ###
