"""Add role column to users table

Revision ID: ef6a021586c8
Revises: 2b029f03258c
Create Date: 2026-01-23 16:21:50.594927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'ef6a021586c8'
down_revision: Union[str, Sequence[str], None] = '2b029f03258c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)

    # Set default role for existing users
    op.execute("UPDATE users SET role = 'admin' WHERE role IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
